### Integer Scanner with Generators (Python)

The *scanner* of a compiler takes a sequence of characters and provides the *parser* with a sequence of symbols (tokens). The scanner can be naturally implemented as a coroutine. Here, we consider the input to the scanner to be a string consisting of integers separated by blanks (or other characters that are not digits; the details don't matter here). There can also be leading and trailing blanks. Calling `scan(s)` should return a generator object such that subsequent calls to `next` return the next integer in the string if there is one. Complete the code below! Hint: the solution can be expressed in five lines of code.

In [31]:
def scan(s: str):
    sl = s.split()
    for num in sl: yield int(num)

In [32]:
p = scan(" 01 234  56   789 ")
next(p), next(p), next(p), next(p)

(1, 234, 56, 789)

The above cell should output `(1, 234, 56, 789)`; subsequent calls to `next` would result in an error. You can use the following cell for testing:

In [33]:
list(scan("01 234 56 789"))

[1, 234, 56, 789]

The expected output is `[1, 234, 56, 789]`. Your implementation must pass the test below:

In [34]:
from types import GeneratorType
p = scan("01 234 56 789")
assert isinstance(p, GeneratorType)
assert list(p) == [1, 234, 56, 789]
assert list(scan(" 01 234  56   789 ")) == [1, 234, 56, 789]